baseURL = "https://knowledgehubs.github.io/engine/"
languageCode = "en-us"
title = "Landing Page Engine"
canonifyURLs = true

[params]
  # ğŸ•¹ï¸ Ù„ÙˆØ­Ø© ØªØ­ÙƒÙ… ØªØºÙŠÙŠØ± Ø§Ù„Ù€ Skin
  skin = "dentist" # Ø§Ù„Ø®ÙŠØ§Ø± Ø§Ù„Ø§ÙØªØ±Ø§Ø¶ÙŠ: Ø¥Ù…Ø§ "dentist" Ø£Ùˆ "realestate"

[server]
  disableFastRender = true
